[package]
name = "http-profiler"
version = "0.1.0"
authors = ["owen8877 <owentoget@yeah.net>"]
edition = "2018"


[dependencies]
env_logger = "*"
getopts = "*"
log = "*"
openssl = "0.10.30"
regex = "*"